name: tesoreria_iglesia
description: "App de tesoreria para la iglesia."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.11.0
  cloud_firestore: ^6.6.0
  firebase_auth: ^6.5.4
  pdf: ^3.12.0
  printing: ^5.14.3
  excel: ^4.0.6
  path_provider: ^2.1.6
  universal_html: ^2.3.0
  image_picker: ^1.2.2
  firebase_storage: ^13.4.3
  file_picker: ^11.0.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
